name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # 每天凌晨自动更新一次
  workflow_dispatch:              # 支持手动点按钮更新
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: NoHeartPen
          template: classic
          base: header, activity, community, repositories, metadata
          # 排除非核心语言
          plugin_languages: yes
          plugin_languages_ignored: >-
            tex, shell, html, css, tcl, procfile, batchfile, vbscript
          plugin_languages_details: percentage
          config_timezone: Asia/Shanghai
